10/12/24 (06:24:47) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (07:34:49) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (07:35:05) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (12:39:39) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (13:31:48) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (15:08:51) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (15:10:37) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (15:12:18) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (15:14:31) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (15:15:20) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (15:16:26) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (15:28:46) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (15:32:32) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
10/12/24 (16:05:51) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (11:02:48) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (16:55:12) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (18:13:59) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (18:14:07) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (18:29:20) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (19:10:10) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (19:11:05) | ERROR: Exception when sending signal 9 to pid 593
11/12/24 (19:11:05) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (19:11:12) | ERROR: Exception when sending signal 9 to pid 593
11/12/24 (19:11:12) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (20:43:24) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (20:43:58) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (23:20:16) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (23:31:40) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (23:58:04) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (23:58:09) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (23:58:57) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
11/12/24 (23:59:23) | ERROR: Exception when sending signal 9 to pid 1149
11/12/24 (23:59:23) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (23:59:24) | ERROR: Exception when sending signal 9 to pid 1149
11/12/24 (23:59:24) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (23:59:33) | ERROR: Exception when sending signal 9 to pid 1149
11/12/24 (23:59:33) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (23:59:35) | ERROR: Exception when sending signal 9 to pid 1149
11/12/24 (23:59:35) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (23:59:36) | ERROR: Exception when sending signal 9 to pid 1149
11/12/24 (23:59:36) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (23:59:36) | ERROR: Exception when sending signal 9 to pid 1149
11/12/24 (23:59:36) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (23:59:37) | ERROR: Exception when sending signal 9 to pid 1149
11/12/24 (23:59:37) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (23:59:38) | ERROR: Exception when sending signal 9 to pid 1149
11/12/24 (23:59:38) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (23:59:38) | ERROR: Exception when sending signal 9 to pid 1149
11/12/24 (23:59:38) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (23:59:39) | ERROR: Exception when sending signal 9 to pid 1149
11/12/24 (23:59:39) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (23:59:39) | ERROR: Exception when sending signal 9 to pid 1149
11/12/24 (23:59:39) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
11/12/24 (23:59:41) | ERROR: Exception when sending signal 2 to pid 1149
11/12/24 (23:59:41) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/sbin/bpytop", line 5479, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
12/12/24 (00:02:18) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
12/12/24 (01:51:40) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
12/12/24 (02:52:54) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
12/12/24 (20:46:10) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
12/12/24 (23:23:33) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
13/12/24 (13:43:17) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
13/12/24 (15:34:34) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
13/12/24 (18:56:40) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
15/12/24 (12:13:03) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
15/12/24 (18:38:38) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
15/12/24 (23:22:40) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
15/12/24 (23:22:40) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/sbin/bpytop", line 2959, in _runner
    collector._draw()
  File "/sbin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/sbin/bpytop", line 2739, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Sign not allowed in string format specifier
15/12/24 (23:22:40) | WARNING: Exiting with errorcode (1). Runtime 0:00:00 

15/12/24 (23:22:47) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
16/12/24 (23:09:15) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
17/12/24 (14:43:50) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
17/12/24 (15:21:08) | ERROR: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
Traceback (most recent call last):
  File "/sbin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/anharsaja/.config/bpytop/themes'
